-- MySQL Script generated by MySQL Workbench
-- Sun May 15 20:14:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_velasVelasquez
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_velasVelasquez
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_velasVelasquez` DEFAULT CHARACTER SET utf8 ;
USE `db_velasVelasquez` ;

-- -----------------------------------------------------
-- Table `db_velasVelasquez`.`tb_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_velasVelasquez`.`tb_producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `titulo_producto` VARCHAR(50) NOT NULL,
  `descripcion_producto` VARCHAR(500) NULL,
  `precio_producto` DECIMAL(8,2) NOT NULL,
  `estado_producto` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_velasVelasquez`.`tb_existencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_velasVelasquez`.`tb_existencias` (
  `id_existencia` INT NOT NULL AUTO_INCREMENT,
  `id_producto_existencias` INT NOT NULL,
  `cantidad_existencias` VARCHAR(45) NOT NULL,
  `fecha_existencias` DATETIME NULL,
  PRIMARY KEY (`id_existencia`),
  INDEX `fk_tb_existencias_tb_producto_idx` (`id_producto_existencias`),
  CONSTRAINT `fk_tb_existencias_tb_producto`
    FOREIGN KEY (`id_producto_existencias`)
    REFERENCES `db_velasVelasquez`.`tb_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_velasVelasquez`.`tb_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_velasVelasquez`.`tb_venta` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATETIME NOT NULL,
  `valor_total_venta` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id_venta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_velasVelasquez`.`tb_detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_velasVelasquez`.`tb_detalle_venta` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_venta_detalle` INT NOT NULL,
  `id_producto_detalle` INT NOT NULL,
  `cantidad_detalle` INT NOT NULL,
  `impuestos_detalle` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `fk_tb_detalle_venta_tb_producto1_idx` (`id_producto_detalle`),
  INDEX `fk_tb_detalle_venta_tb_venta1_idx` (`id_venta_detalle`),
  CONSTRAINT `fk_tb_detalle_venta_tb_producto1`
    FOREIGN KEY (`id_producto_detalle`)
    REFERENCES `db_velasVelasquez`.`tb_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_detalle_venta_tb_venta1`
    FOREIGN KEY (`id_venta_detalle`)
    REFERENCES `db_velasVelasquez`.`tb_venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_velasVelasquez`.`tb_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_velasVelasquez`.`tb_carrito` (
  `id_carrito` INT NOT NULL AUTO_INCREMENT,
  `fecha_carriito` DATETIME NOT NULL,
  PRIMARY KEY (`id_carrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_velasVelasquez`.`tb_detalle_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_velasVelasquez`.`tb_detalle_carrito` (
  `id_detalle_carrito` INT NOT NULL AUTO_INCREMENT,
  `tb_carrito_id_carrito` INT NOT NULL,
  `tb_producto_id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_detalle_carrito`),
  INDEX `fk_tb_detalle_carrito_tb_carrito1_idx` (`tb_carrito_id_carrito`),
  INDEX `fk_tb_detalle_carrito_tb_producto1_idx` (`tb_producto_id_producto`),
  CONSTRAINT `fk_tb_detalle_carrito_tb_carrito1`
    FOREIGN KEY (`tb_carrito_id_carrito`)
    REFERENCES `db_velasVelasquez`.`tb_carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_detalle_carrito_tb_producto1`
    FOREIGN KEY (`tb_producto_id_producto`)
    REFERENCES `db_velasVelasquez`.`tb_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
